output_dir: "outputs"
pretrained_model_path: "ckpts/StableDiffusion/stable-diffusion-v1-5"

unet_additional_kwargs:
  use_motion_module              : true
  motion_module_resolutions      : [ 1,2,4,8 ]
  unet_use_cross_frame_attention : false
  unet_use_temporal_attention    : false

  motion_module_type: Vanilla
  motion_module_kwargs:
    num_attention_heads                : 8
    num_transformer_block              : 1
    attention_block_types              : [ "Temporal_Self", "Temporal_Self" ]
    temporal_position_encoding         : true
    temporal_position_encoding_max_len : 24
    temporal_attention_dim_div         : 1
    zero_initialize                    : true

noise_scheduler_kwargs:
  num_train_timesteps: 1000
  beta_start:          0.00085
  beta_end:            0.012
  beta_schedule:       "linear"
  steps_offset:        1
  clip_sample:         false

train_data:
  csv_path:        "datasets/WEB360/WEB360_360TF.csv"
  video_folder:    "datasets/WEB360/videos_512x1024x100"
  flow_folder:     "datasets/WEB360/flows_512x1024x100"
  sample_size:     512
  sample_stride:   4
  sample_n_frames: 16

validation_data:
  prompts:
    - "an aerial view of the top of a snow covered mountain range, with the sun shining over it"
  num_inference_steps: 25
  guidance_scale: 8.

unet_checkpoint_path: ""
motion_module_checkpoint_path: "ckpts/Motion_Module/mm_sd_v14.ckpt"

learning_rate:    1.e-5
train_batch_size: 1

max_train_epoch:      -1
max_train_steps:      100000
checkpointing_epochs: -1
checkpointing_steps:  9999

validation_steps:       999
validation_steps_tuple: [2, 49, 99, 199, 299, 499]

global_seed: 42
mixed_precision_training: true
enable_xformers_memory_efficient_attention: true

is_debug: false